name: Automation Practice Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
      
    - name: Run your tests
      run: pytest --tracing=retain-on-failure --ctrf report.json
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/

    - name: Setup Node
      uses: actions/setup-node@v4
      if: ${{ !cancelled() }}
      with:
        node-version: 'latest'

    - name: Install Ctrf
      if: ${{ !cancelled() }}
      run: |
        npm install github-actions-ctrf

    - name: Generate Summary Report
      if: ${{ !cancelled() }}
      run: |
        npx github-actions-ctrf logs/ctrf-report.json
